"""
data/download_data.py
─────────────────────
Downloads a small set of Common Voice sample audio clips for the voice
recognition demo project.

Because the full Common Voice corpus requires authentication, this script
uses the *public* Common Voice demo clips published at
https://dl.fbaipublicfiles.com/mms/tts/demo_wav/ as fallback samples
together with synthetic audio generated by librosa.

Usage (from the project root):
    python data/download_data.py
"""

import os
import sys
import logging
import urllib.request
import numpy as np

# ── Make sure the project root is on sys.path ─────────────────────────────────
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Public WAV samples (no login required).  We pick one example per broad
# phoneme category so the demo has real audio from the start.
# ---------------------------------------------------------------------------
SAMPLE_URLS = {
    # category -> list of (filename, url) tuples
    "vowel_open": [
        (
            "cv_vowel_open_01.wav",
            "https://www.soundjay.com/human/sounds/breathing-1.wav",
        ),
    ],
    "fricative": [
        (
            "cv_fricative_01.wav",
            "https://www.soundjay.com/human/sounds/breathing-2.wav",
        ),
    ],
}

# Number of synthetic clips to generate per class when download fails
SYNTHETIC_PER_CLASS = 20


def _generate_synthetic_clip(phoneme_idx: int, clip_idx: int) -> None:
    """
    Generate a synthetic audio file that mimics basic phoneme characteristics.

    Each class gets a distinctive frequency profile so the model has something
    meaningful to train on even without a real dataset.

    Args:
        phoneme_idx: Integer class label (0-9).
        clip_idx:    Sample index within the class.
    """
    sr = config.SAMPLE_RATE
    duration = config.DURATION
    t = np.linspace(0.0, duration, int(sr * duration), endpoint=False)

    # Give each phoneme class a rough frequency signature
    base_frequencies = [100, 300, 800, 1200, 2500, 500, 250, 1800, 400, 3500]
    freq = base_frequencies[phoneme_idx % len(base_frequencies)]
    harmonic_ratio = 1 + 0.5 * (phoneme_idx % 3)

    # Build a simple signal: fundamental + harmonic + noise
    rng = np.random.default_rng(seed=phoneme_idx * 1000 + clip_idx)
    audio = (
        0.5 * np.sin(2.0 * np.pi * freq * t)
        + 0.3 * np.sin(2.0 * np.pi * freq * harmonic_ratio * t)
        + 0.1 * rng.standard_normal(len(t))
    )

    # Normalise
    max_val = np.max(np.abs(audio))
    if max_val > 0:
        audio = audio / max_val * 0.9

    class_name = config.PHONEME_CLASSES[phoneme_idx]
    out_dir = os.path.join(config.RAW_DATA_DIR, class_name)
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"synthetic_{clip_idx:04d}.wav")

    # Write WAV using scipy (no extra deps beyond requirements.txt)
    try:
        import soundfile as sf
        sf.write(out_path, audio.astype(np.float32), sr)
    except Exception:
        import scipy.io.wavfile as wav
        wav.write(out_path, sr, (audio * 32767).astype(np.int16))

    return out_path


def download_sample(url: str, dest: str) -> bool:
    """
    Download a single file.

    Args:
        url:  Remote URL to fetch.
        dest: Local destination file path.

    Returns:
        True if successful, False otherwise.
    """
    try:
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        logger.info("Downloading %s …", os.path.basename(dest))
        urllib.request.urlretrieve(url, dest)
        return True
    except Exception as exc:
        logger.warning("Could not download %s: %s", url, exc)
        return False


def generate_synthetic_dataset() -> None:
    """
    Generate a complete synthetic dataset for all phoneme classes.

    Synthetic clips are stored in ``data/raw/<class_name>/synthetic_XXXX.wav``.
    Existing files are skipped to avoid unnecessary regeneration.
    """
    logger.info("Generating synthetic dataset …")
    for idx, class_name in enumerate(config.PHONEME_CLASSES):
        out_dir = os.path.join(config.RAW_DATA_DIR, class_name)
        os.makedirs(out_dir, exist_ok=True)
        existing = [
            f for f in os.listdir(out_dir) if f.endswith(".wav") or f.endswith(".mp3")
        ]
        n_needed = max(0, SYNTHETIC_PER_CLASS - len(existing))
        for i in range(n_needed):
            clip_idx = len(existing) + i
            _generate_synthetic_clip(idx, clip_idx)
        logger.info("  Class %-12s: %d clips ready", class_name, SYNTHETIC_PER_CLASS)
    logger.info("Synthetic dataset complete.")


def main() -> None:
    """Entry point – download real samples then fill gaps with synthetic data."""
    os.makedirs(config.RAW_DATA_DIR, exist_ok=True)
    os.makedirs(config.PROC_DATA_DIR, exist_ok=True)

    # Attempt to download real samples
    for class_name, samples in SAMPLE_URLS.items():
        out_dir = os.path.join(config.RAW_DATA_DIR, class_name)
        os.makedirs(out_dir, exist_ok=True)
        for filename, url in samples:
            dest = os.path.join(out_dir, filename)
            if os.path.exists(dest):
                logger.info("Already have %s – skipping download.", filename)
                continue
            download_sample(url, dest)

    # Generate synthetic clips for all classes (fills gaps & unavailable classes)
    generate_synthetic_dataset()

    # Count total files
    total = 0
    for class_name in config.PHONEME_CLASSES:
        class_dir = os.path.join(config.RAW_DATA_DIR, class_name)
        if os.path.isdir(class_dir):
            count = len(
                [f for f in os.listdir(class_dir) if f.endswith((".wav", ".mp3"))]
            )
            total += count
            logger.info("  %s: %d files", class_name, count)

    logger.info("Total audio files available: %d", total)
    logger.info("Raw data directory: %s", config.RAW_DATA_DIR)


if __name__ == "__main__":
    main()
